"""Evidence Pack: the curated, provenance-complete set of facts a pitch may draw on.

Every item has an id (E1..En), the structured FeatureFact, and its SourceRefs. The pitch generator
may only make policy statements that cite these ids; the auditor maps ids back to chunks.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

from app.models.client import CompanyProfile, Exposure, FactKind, WebSource
from app.models.fit import PolicyFitResult, PolicyGap, Recommendation, ScenarioOutcome
from app.models.policy import ComparisonMatrix, CoverageStatus, FeatureFact, PolicyDocument, SourceRef
from app.policies.features import FEATURE_LABELS


class EvidenceItem(BaseModel):
    evidence_id: str
    policy_id: str
    policy_name: str
    feature_key: str
    feature_label: str
    status: CoverageStatus
    statement: str  # concise, faithful summary for the writer
    conditions: list[str] = Field(default_factory=list)
    exclusions: list[str] = Field(default_factory=list)
    variant_scope: str | None = None
    sources: list[SourceRef] = Field(default_factory=list)
    material: bool = True

    @property
    def chunk_ids(self) -> list[str]:
        return [s.chunk_id for s in self.sources]


class CompanyEvidence(BaseModel):
    """A verified company fact (C1..Cn) with the web pages it was read from, so a company bullet can cite them."""

    evidence_id: str
    text: str
    sources: list[WebSource] = Field(default_factory=list)

    @property
    def urls(self) -> list[str]:
        return [s.url for s in self.sources if s.url.startswith(("http://", "https://"))]


class EvidencePack(BaseModel):
    recommended_policy_id: str
    items: list[EvidenceItem]
    comparison_notes: list[str] = Field(default_factory=list)  # deterministic statements vs other policies
    gaps: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    company_evidence: list[CompanyEvidence] = Field(default_factory=list)
    company_inferences: list[str] = Field(default_factory=list)

    def by_id(self) -> dict[str, EvidenceItem]:
        return {i.evidence_id: i for i in self.items}

    def company_by_id(self) -> dict[str, CompanyEvidence]:
        return {c.evidence_id: c for c in self.company_evidence}


def _statement(fact: FeatureFact, label: str) -> str:
    parts = [fact.value or label]
    if fact.limit and fact.limit not in parts[0]:
        parts.append(f"Limit: {fact.limit}")
    if fact.waiting_period and fact.waiting_period not in parts[0]:
        parts.append(f"Waiting period: {fact.waiting_period}")
    if fact.copay and fact.copay not in parts[0]:
        parts.append(f"Co-pay: {fact.copay}")
    if fact.deductible and fact.deductible not in parts[0]:
        parts.append(f"Deductible: {fact.deductible}")
    return ". ".join(p.rstrip(".") for p in parts if p) + "."


def build_evidence_pack(
    recommendation: Recommendation,
    matrix: ComparisonMatrix,
    exposures: list[Exposure],
    outcomes: list[ScenarioOutcome],
    gaps: list[PolicyGap],
    fits: list[PolicyFitResult],
    docs: dict[str, PolicyDocument],
    profile: CompanyProfile,
    max_items: int = 18,
) -> EvidencePack:
    pid = recommendation.recommended_policy_id
    # features ordered by exposure priority, then remaining matrix features
    ordered: list[str] = []
    for e in sorted(exposures, key=lambda x: -x.priority):
        for k in e.feature_keys:
            if k not in ordered:
                ordered.append(k)
    for k in matrix.features:
        if k not in ordered:
            ordered.append(k)

    items: list[EvidenceItem] = []
    n = 0
    for k in ordered:
        cell = matrix.cells.get(k, {}).get(pid)
        if not cell:
            continue
        fact = cell.fact
        if fact.coverage_status in {CoverageStatus.NOT_FOUND, CoverageStatus.UNKNOWN} or not fact.sources:
            continue
        n += 1
        items.append(
            EvidenceItem(
                evidence_id=f"E{n}",
                policy_id=pid,
                policy_name=docs[pid].policy_name if pid in docs else pid,
                feature_key=k,
                feature_label=FEATURE_LABELS.get(k, k),
                status=fact.coverage_status,
                statement=_statement(fact, FEATURE_LABELS.get(k, k)),
                conditions=list(fact.conditions)[:4],
                exclusions=list(fact.exclusions)[:4],
                variant_scope=fact.variant_scope,
                sources=fact.sources[:3],
            )
        )
        if len(items) >= max_items:
            break

    # deterministic comparison notes (never generated by the LLM)
    notes: list[str] = []
    others = [p for p in matrix.policy_ids if p != pid]
    for k in ordered[:10]:
        row = matrix.cells.get(k, {})
        mine = row.get(pid)
        if not mine or mine.status in {CoverageStatus.NOT_FOUND, CoverageStatus.UNKNOWN}:
            continue
        weaker = [docs[o].policy_name if o in docs else o for o in others if row.get(o) and row[o].status in {CoverageStatus.EXCLUDED, CoverageStatus.NOT_FOUND, CoverageStatus.ADD_ON}]
        if weaker and mine.status in {CoverageStatus.COVERED, CoverageStatus.CONDITIONAL}:
            notes.append(f"{FEATURE_LABELS.get(k, k)}: stated as {mine.status.value.lower().replace('_', ' ')} in {mine.fact.sources[0].policy_name if mine.fact.sources else pid}; not found, excluded or add-on in {', '.join(weaker)} (per brochures).")
    fit = next((f for f in fits if f.policy_id == pid), None)
    if fit:
        notes.append(f"Deterministic policy-fit score {fit.score}/100 ({fit.confidence.lower()} evidence confidence), a decision-support metric, not a statement of truth.")
        if fit.close_call_with:
            notes.append("Close call with: " + ", ".join(docs[c].policy_name if c in docs else c for c in fit.close_call_with) + ". Advisor judgement recommended.")

    gap_lines = [g.detail for g in gaps if g.policy_id == pid][:6]
    company = [CompanyEvidence(evidence_id=f"C{i}", text=f.text, sources=f.sources) for i, f in enumerate([f for f in profile.facts if f.kind == FactKind.FACT][:8], 1)]
    infers = [f"{f.text} ({f.kind.value.lower()})" for f in profile.facts if f.kind in {FactKind.INFERENCE, FactKind.ASSUMPTION}][:6]
    return EvidencePack(
        recommended_policy_id=pid,
        items=items,
        comparison_notes=notes,
        gaps=gap_lines,
        assumptions=list(recommendation.assumptions) + list(recommendation.caveats),
        company_evidence=company,
        company_inferences=infers,
    )
